/* Travel Assistant Pro 2.2 - cloud-backed customer CRM */
(function(global,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;global.TravelCRM=api})(typeof window!=='undefined'?window:globalThis,function(){
'use strict';
const clean=v=>String(v||'').trim(),escapeHtml=v=>clean(v).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char])),terms=v=>clean(v).split(/[、,，\s]+/).map(x=>x.toLowerCase()).filter(Boolean);
function scoreTrip(client,trip){const text=[trip.title,trip.subtitle,trip.airline,trip.price,trip.dates,...(trip.highlights||[])].join(' ').toLowerCase(),matched=terms(client.likes).filter(x=>text.includes(x)),conflicts=terms(client.avoids).filter(x=>text.includes(x));return{score:Math.max(0,matched.length*25-conflicts.length*40),matched,conflicts,suitable:matched.length>0&&!conflicts.length}}
function mergeClients(local,cloud){const map=new Map();[...(local||[]),...(cloud||[])].forEach(client=>{if(!client?.id)return;const old=map.get(client.id);if(!old||String(client.updated||'')>=String(old.updated||''))map.set(client.id,client)});return [...map.values()].sort((a,b)=>String(b.updated||'').localeCompare(String(a.updated||'')))}
function install(){
  const panel=document.querySelector('.wrap > .panel');if(!panel||document.getElementById('crmSection'))return;
  const section=document.createElement('section');section.id='crmSection';section.className='section';section.innerHTML=`<h2>客戶 CRM <span class="badge">V2.2 雲端安全版</span></h2><div class="hint">客戶基本資料、追蹤狀態與推薦紀錄都會同步 Supabase，其他同事與裝置也能讀取。</div><div class="grid2" style="margin-top:12px"><div><label>客戶姓名</label><input id="crmName" placeholder="例如：王先生"></div><div><label>聯絡方式</label><input id="crmContact" placeholder="電話或 LINE"></div></div><div class="grid2" style="margin-top:10px"><div><label>喜歡的地區／特色</label><input id="crmLikes" placeholder="日本、賞楓、長榮、溫泉"></div><div><label>不喜歡／需要避開</label><input id="crmAvoids" placeholder="購物、紅眼航班、走路多"></div></div><div class="grid2" style="margin-top:10px"><div><label>目前狀態</label><select id="crmStage"><option>詢問中</option><option>考慮中</option><option>已報名</option><option>暫緩</option></select></div><div><label>下次追蹤日</label><input id="crmFollowUp" type="date"></div></div><label style="margin-top:10px">已推薦團號</label><input id="crmRecommended" placeholder="例如：PUS05BX261002J、FUK05BR261206FU"><label style="margin-top:10px">備註</label><textarea id="crmNotes" placeholder="家庭成員、常用預算、希望出發月份等"></textarea><div class="btnrow"><button class="primary" id="crmSave">儲存客戶</button><button id="crmSync">同步雲端 CRM</button><button id="crmCheck">檢查目前行程是否適合</button><button id="crmRematchAll">重新配對所有客戶</button></div><div class="btnrow"><button id="crmExport">匯出 CRM JSON</button><button id="crmCreateSnapshot">建立 CRM 雲端備份</button><select id="crmSnapshotSelect" aria-label="選擇 CRM 備份"><option value="">選擇最近備份</option></select><button id="crmRestoreSnapshot">還原 CRM 備份</button></div><div id="crmStatus" class="status"></div><div id="crmList" class="hint" style="margin-top:12px"></div>`;panel.appendChild(section);
  const $=id=>document.getElementById(id),key='travelAssistantV2Clients',load=()=>{try{const v=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(v)?v:[]}catch(_){return[]}},saveLocal=v=>{localStorage.setItem(key,JSON.stringify(v));render()},show=(message,type='ok')=>{$('crmStatus').textContent=message;$('crmStatus').className='status show '+type};
  const request=async(url,options={})=>{const response=await fetch(url,{headers:{accept:'application/json',...(options.body?{'content-type':'application/json'}:{})},...options}),payload=await response.json();if(!response.ok||!payload.ok)throw new Error(payload.error?.message||'雲端 CRM 連線失敗');return payload.data};
  const trip=()=>({title:$('mainTitle').value,subtitle:$('subtitle').value,airline:$('airline').value,price:$('price').value,dates:$('dates').value,highlights:$('highlights').value.split(/\r?\n/).filter(Boolean)}),fill=c=>{$('crmName').value=c.name||'';$('crmContact').value=c.contact||'';$('crmLikes').value=c.likes||'';$('crmAvoids').value=c.avoids||'';$('crmStage').value=c.stage||'詢問中';$('crmFollowUp').value=c.followUp||'';$('crmRecommended').value=c.recommended||'';$('crmNotes').value=c.notes||''};
  async function syncCloud(silent=false){try{if(!silent)show('正在同步雲端 CRM…','warn');const local=load(),data=await request('/api/cloud/crm');if(!data.configured){if(!silent)show('Supabase 尚未連接，目前先保存在此瀏覽器。','warn');return false}const cloud=data.clients||[],merged=mergeClients(local,cloud),cloudById=new Map(cloud.map(client=>[client.id,client]));const uploads=merged.filter(client=>!cloudById.has(client.id)||String(client.updated||'')>String(cloudById.get(client.id).updated||''));await Promise.all(uploads.map(client=>request('/api/cloud/crm',{method:'POST',body:JSON.stringify(client)})));saveLocal(merged);if(!silent)show(`雲端 CRM 同步完成，共 ${merged.length} 位客戶。`);return true}catch(error){if(!silent)show(`雲端同步失敗，資料仍保存在此瀏覽器：${error.message}`,'warn');return false}}
  function render(){const list=$('crmList'),clients=load();list.innerHTML='';if(!clients.length){list.textContent='尚未建立客戶資料。';return}clients.forEach(c=>{const row=document.createElement('div');row.className='dbitem';const info=document.createElement('div');info.innerHTML=`<div class="dbtitle">${escapeHtml(c.name)}</div><div class="dbmeta">${escapeHtml(c.stage)||'詢問中'}｜追蹤：${escapeHtml(c.followUp)||'未設定'}｜喜歡：${escapeHtml(c.likes)||'未填'}・避開：${escapeHtml(c.avoids)||'未填'}</div><div class="small" style="margin-top:5px;color:#52666a">備註：${escapeHtml(c.notes)||'未填'}</div>${c.suggestions?.length?`<div class="small" style="color:#087a55">新配對：${c.suggestions.map(escapeHtml).join('、')}</div>`:''}`;const actions=document.createElement('div');actions.className='dbactions';const edit=document.createElement('button');edit.textContent='載入';edit.onclick=()=>fill(c);const del=document.createElement('button');del.textContent='刪除';del.onclick=async()=>{if(!confirm('確定刪除此客戶？'))return;saveLocal(load().filter(x=>x.id!==c.id));try{await request('/api/cloud/crm?id='+encodeURIComponent(c.id),{method:'DELETE'});show('客戶資料已從瀏覽器與雲端刪除。')}catch(error){show(`本機已刪除，但雲端刪除失敗：${error.message}`,'warn')}};actions.append(edit,del);row.append(info,actions);list.appendChild(row)})}
  $('crmSave').onclick=async()=>{const name=clean($('crmName').value);if(!name){show('請先填寫客戶姓名。','warn');return}const all=load(),old=all.find(x=>x.name===name),record={id:old?.id||String(Date.now()),name,contact:clean($('crmContact').value),likes:clean($('crmLikes').value),avoids:clean($('crmAvoids').value),stage:$('crmStage').value,followUp:$('crmFollowUp').value,recommended:clean($('crmRecommended').value),notes:clean($('crmNotes').value),suggestions:old?.suggestions||[],updated:new Date().toISOString()};saveLocal(old?all.map(x=>x.id===old.id?record:x):[record,...all]);show('客戶資料已保存在瀏覽器，正在同步雲端…','warn');try{await request('/api/cloud/crm',{method:'POST',body:JSON.stringify(record)});show('客戶資料與追蹤狀態已同步至 Supabase。')}catch(error){show(`已保存在瀏覽器，但雲端同步失敗：${error.message}`,'warn')}};
  $('crmSync').onclick=()=>syncCloud();
  $('crmRematchAll').onclick=async()=>{let db=[];try{db=JSON.parse(localStorage.getItem('travelV10Db')||'[]')}catch(_){}const clients=load().map(client=>({...client,suggestions:db.map(item=>({item,result:scoreTrip(client,item)})).filter(x=>x.result.suitable).sort((a,b)=>b.result.score-a.result.score).slice(0,3).map(x=>x.item.code),updated:new Date().toISOString()}));saveLocal(clients);try{await Promise.all(clients.map(client=>request('/api/cloud/crm',{method:'POST',body:JSON.stringify(client)})));show(`已重新配對 ${clients.length} 位客戶並同步雲端。`)}catch(error){show(`重新配對已保存在瀏覽器，但雲端同步失敗：${error.message}`,'warn')}};
  $('crmExport').onclick=()=>{const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),clients:load()},null,2)],{type:'application/json'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`travel-crm-${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(link.href);show(`已匯出 ${load().length} 位客戶。`)};
  async function loadSnapshots(){try{const data=await request('/api/cloud/crm/snapshots'),rows=data.snapshots||[];$('crmSnapshotSelect').innerHTML='<option value="">選擇最近備份</option>'+rows.map(row=>`<option value="${row.id}">${new Date(row.created_at).toLocaleString('zh-TW')}｜${row.client_count} 位</option>`).join('')}catch(_){$('crmSnapshotSelect').innerHTML='<option value="">備份清單讀取失敗</option>'}}
  $('crmCreateSnapshot').onclick=async()=>{try{await syncCloud(true);const data=await request('/api/cloud/crm/snapshot',{method:'POST',body:'{}'});show(`CRM 雲端備份完成，共 ${data.clientCount} 位客戶。`);await loadSnapshots()}catch(error){show(`CRM 備份失敗：${error.message}`,'warn')}};
  $('crmRestoreSnapshot').onclick=async()=>{const id=$('crmSnapshotSelect').value;if(!id){show('請先選擇 CRM 備份。','warn');return}if(prompt('還原會以備份內容取代目前 CRM。請輸入「還原」確認：')!=='還原')return;try{const data=await request('/api/cloud/crm/restore',{method:'POST',body:JSON.stringify({id})});saveLocal(data.clients||[]);show(`CRM 備份還原完成，共恢復 ${data.restored} 位客戶。`)}catch(error){show(`CRM 備份還原失敗：${error.message}`,'warn')}};
  $('crmCheck').onclick=()=>{const r=scoreTrip({likes:$('crmLikes').value,avoids:$('crmAvoids').value},trip());show(r.conflicts.length?`不建議直接推薦：命中避開條件「${r.conflicts.join('、')}」。`:(r.matched.length?`適合推薦：符合「${r.matched.join('、')}」，適配分數 ${r.score}。`:'目前沒有足夠的偏好命中，建議再確認需求。'),r.suitable?'ok':'warn')};
  render();loadSnapshots();syncCloud(true);
}
if(typeof document!=='undefined'){if(document.querySelector('.wrap > .panel'))install();else document.addEventListener('DOMContentLoaded',install)}
return{scoreTrip,mergeClients,escapeHtml};
});
