/* Travel Assistant Pro 2.2 - cloud-backed customer CRM */
(function(global,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;global.TravelCRM=api})(typeof window!=='undefined'?window:globalThis,function(){
'use strict';
const clean=v=>String(v||'').trim(),terms=v=>clean(v).split(/[、,，\s]+/).map(x=>x.toLowerCase()).filter(Boolean);
function scoreTrip(client,trip){const text=[trip.title,trip.subtitle,trip.airline,trip.price,trip.dates,...(trip.highlights||[])].join(' ').toLowerCase(),matched=terms(client.likes).filter(x=>text.includes(x)),conflicts=terms(client.avoids).filter(x=>text.includes(x));return{score:Math.max(0,matched.length*25-conflicts.length*40),matched,conflicts,suitable:matched.length>0&&!conflicts.length}}
function mergeClients(local,cloud){const map=new Map();[...(local||[]),...(cloud||[])].forEach(client=>{if(!client?.id)return;const old=map.get(client.id);if(!old||String(client.updated||'')>=String(old.updated||''))map.set(client.id,client)});return [...map.values()].sort((a,b)=>String(b.updated||'').localeCompare(String(a.updated||'')))}
function install(){
  const panel=document.querySelector('.wrap > .panel');if(!panel||document.getElementById('crmSection'))return;
  const section=document.createElement('section');section.id='crmSection';section.className='section';section.innerHTML=`<h2>客戶 CRM <span class="badge">V2.1 雲端</span></h2><div class="hint">記錄客戶喜好與避開條件，載入行程後可快速判斷是否適合。已連接 Supabase 時會自動雲端同步，其他同事與裝置也能讀取。</div><div class="grid2" style="margin-top:12px"><div><label>客戶姓名</label><input id="crmName" placeholder="例如：王先生"></div><div><label>聯絡方式</label><input id="crmContact" placeholder="電話或 LINE"></div></div><div class="grid2" style="margin-top:10px"><div><label>喜歡的地區／特色</label><input id="crmLikes" placeholder="日本、賞楓、長榮、溫泉"></div><div><label>不喜歡／需要避開</label><input id="crmAvoids" placeholder="購物、紅眼航班、走路多"></div></div><label style="margin-top:10px">備註</label><textarea id="crmNotes" placeholder="家庭成員、常用預算、希望出發月份等"></textarea><div class="btnrow"><button class="primary" id="crmSave">儲存客戶</button><button id="crmSync">同步雲端 CRM</button><button id="crmCheck">檢查目前行程是否適合</button></div><div id="crmStatus" class="status"></div><div id="crmList" class="hint" style="margin-top:12px"></div>`;panel.appendChild(section);
  const $=id=>document.getElementById(id),key='travelAssistantV2Clients',load=()=>{try{const v=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(v)?v:[]}catch(_){return[]}},saveLocal=v=>{localStorage.setItem(key,JSON.stringify(v));render()},show=(message,type='ok')=>{$('crmStatus').textContent=message;$('crmStatus').className='status show '+type};
  const request=async(url,options={})=>{const response=await fetch(url,{headers:{accept:'application/json',...(options.body?{'content-type':'application/json'}:{})},...options}),payload=await response.json();if(!response.ok||!payload.ok)throw new Error(payload.error?.message||'雲端 CRM 連線失敗');return payload.data};
  const trip=()=>({title:$('mainTitle').value,subtitle:$('subtitle').value,airline:$('airline').value,price:$('price').value,dates:$('dates').value,highlights:$('highlights').value.split(/\r?\n/).filter(Boolean)}),fill=c=>{$('crmName').value=c.name||'';$('crmContact').value=c.contact||'';$('crmLikes').value=c.likes||'';$('crmAvoids').value=c.avoids||'';$('crmNotes').value=c.notes||''};
  async function syncCloud(silent=false){try{if(!silent)show('正在同步雲端 CRM…','warn');const local=load(),data=await request('/api/cloud/crm');if(!data.configured){if(!silent)show('Supabase 尚未連接，目前先保存在此瀏覽器。','warn');return false}const cloud=data.clients||[],merged=mergeClients(local,cloud),cloudById=new Map(cloud.map(client=>[client.id,client]));const uploads=merged.filter(client=>!cloudById.has(client.id)||String(client.updated||'')>String(cloudById.get(client.id).updated||''));await Promise.all(uploads.map(client=>request('/api/cloud/crm',{method:'POST',body:JSON.stringify(client)})));saveLocal(merged);if(!silent)show(`雲端 CRM 同步完成，共 ${merged.length} 位客戶。`);return true}catch(error){if(!silent)show(`雲端同步失敗，資料仍保存在此瀏覽器：${error.message}`,'warn');return false}}
  function render(){const list=$('crmList'),clients=load();list.innerHTML='';if(!clients.length){list.textContent='尚未建立客戶資料。';return}clients.forEach(c=>{const row=document.createElement('div');row.className='dbitem';const info=document.createElement('div');info.innerHTML=`<div class="dbtitle">${clean(c.name)}</div><div class="dbmeta">喜歡：${clean(c.likes)||'未填'}・避開：${clean(c.avoids)||'未填'}</div>`;const actions=document.createElement('div');actions.className='dbactions';const edit=document.createElement('button');edit.textContent='載入';edit.onclick=()=>fill(c);const del=document.createElement('button');del.textContent='刪除';del.onclick=async()=>{if(!confirm('確定刪除此客戶？'))return;saveLocal(load().filter(x=>x.id!==c.id));try{await request('/api/cloud/crm?id='+encodeURIComponent(c.id),{method:'DELETE'});show('客戶資料已從瀏覽器與雲端刪除。')}catch(error){show(`本機已刪除，但雲端刪除失敗：${error.message}`,'warn')}};actions.append(edit,del);row.append(info,actions);list.appendChild(row)})}
  $('crmSave').onclick=async()=>{const name=clean($('crmName').value);if(!name){show('請先填寫客戶姓名。','warn');return}const all=load(),old=all.find(x=>x.name===name),record={id:old?.id||String(Date.now()),name,contact:clean($('crmContact').value),likes:clean($('crmLikes').value),avoids:clean($('crmAvoids').value),notes:clean($('crmNotes').value),updated:new Date().toISOString()};saveLocal(old?all.map(x=>x.id===old.id?record:x):[record,...all]);show('客戶資料已保存在瀏覽器，正在同步雲端…','warn');try{await request('/api/cloud/crm',{method:'POST',body:JSON.stringify(record)});show('客戶資料已儲存並同步至 Supabase。')}catch(error){show(`已保存在瀏覽器，但雲端同步失敗：${error.message}`,'warn')}};
  $('crmSync').onclick=()=>syncCloud();
  $('crmCheck').onclick=()=>{const r=scoreTrip({likes:$('crmLikes').value,avoids:$('crmAvoids').value},trip());show(r.conflicts.length?`不建議直接推薦：命中避開條件「${r.conflicts.join('、')}」。`:(r.matched.length?`適合推薦：符合「${r.matched.join('、')}」，適配分數 ${r.score}。`:'目前沒有足夠的偏好命中，建議再確認需求。'),r.suitable?'ok':'warn')};
  render();syncCloud(true);
}
if(typeof document!=='undefined'){if(document.querySelector('.wrap > .panel'))install();else document.addEventListener('DOMContentLoaded',install)}
return{scoreTrip,mergeClients};
});
