/* Travel Assistant Pro 2.0 - lightweight customer CRM */
(function(global,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;global.TravelCRM=api})(typeof window!=='undefined'?window:globalThis,function(){
'use strict';const clean=v=>String(v||'').trim();const terms=v=>clean(v).split(/[、,，\s]+/).map(x=>x.toLowerCase()).filter(Boolean);
function scoreTrip(client,trip){const text=[trip.title,trip.subtitle,trip.airline,trip.price,trip.dates,...(trip.highlights||[])].join(' ').toLowerCase(),matched=terms(client.likes).filter(x=>text.includes(x)),conflicts=terms(client.avoids).filter(x=>text.includes(x));return{score:Math.max(0,matched.length*25-conflicts.length*40),matched,conflicts,suitable:matched.length>0&&!conflicts.length}}
function install(){const panel=document.querySelector('.wrap > .panel');if(!panel||document.getElementById('crmSection'))return;const section=document.createElement('section');section.id='crmSection';section.className='section';section.innerHTML=`<h2>客戶 CRM <span class="badge">V2.0</span></h2><div class="hint">記錄客戶喜好與避開條件，載入行程後可快速判斷是否適合。資料只儲存在目前瀏覽器。</div><div class="grid2" style="margin-top:12px"><div><label>客戶姓名</label><input id="crmName" placeholder="例如：王先生"></div><div><label>聯絡方式</label><input id="crmContact" placeholder="電話或 LINE"></div></div><div class="grid2" style="margin-top:10px"><div><label>喜歡的地區／特色</label><input id="crmLikes" placeholder="日本、賞楓、長榮、溫泉"></div><div><label>不喜歡／需要避開</label><input id="crmAvoids" placeholder="購物、紅眼航班、走路多"></div></div><label style="margin-top:10px">備註</label><textarea id="crmNotes" placeholder="家庭成員、常用預算、希望出發月份等"></textarea><div class="btnrow"><button class="primary" id="crmSave">儲存客戶</button><button id="crmCheck">檢查目前行程是否適合</button></div><div id="crmStatus" class="status"></div><div id="crmList" class="hint" style="margin-top:12px"></div>`;panel.appendChild(section);
const $=id=>document.getElementById(id),key='travelAssistantV2Clients',load=()=>{try{return JSON.parse(localStorage.getItem(key)||'[]')}catch(_){return[]}},save=v=>{localStorage.setItem(key,JSON.stringify(v));render()},trip=()=>({title:$('mainTitle').value,subtitle:$('subtitle').value,airline:$('airline').value,price:$('price').value,dates:$('dates').value,highlights:$('highlights').value.split(/\r?\n/).filter(Boolean)}),fill=c=>{$('crmName').value=c.name||'';$('crmContact').value=c.contact||'';$('crmLikes').value=c.likes||'';$('crmAvoids').value=c.avoids||'';$('crmNotes').value=c.notes||''};
function render(){const list=$('crmList'),clients=load();list.innerHTML='';if(!clients.length){list.textContent='尚未建立客戶資料。';return}clients.forEach(c=>{const row=document.createElement('div');row.className='dbitem';const info=document.createElement('div');info.innerHTML=`<div class="dbtitle">${clean(c.name)}</div><div class="dbmeta">喜歡：${clean(c.likes)||'未填'}・避開：${clean(c.avoids)||'未填'}</div>`;const actions=document.createElement('div');actions.className='dbactions';const edit=document.createElement('button');edit.textContent='載入';edit.onclick=()=>fill(c);const del=document.createElement('button');del.textContent='刪除';del.onclick=()=>{if(confirm('確定刪除此客戶？'))save(load().filter(x=>x.id!==c.id))};actions.append(edit,del);row.append(info,actions);list.appendChild(row)})}
$('crmSave').onclick=()=>{const name=clean($('crmName').value);if(!name){$('crmStatus').textContent='請先填寫客戶姓名。';$('crmStatus').className='status show warn';return}const all=load(),old=all.find(x=>x.name===name),record={id:old?.id||String(Date.now()),name,contact:clean($('crmContact').value),likes:clean($('crmLikes').value),avoids:clean($('crmAvoids').value),notes:clean($('crmNotes').value),updated:new Date().toISOString()};save(old?all.map(x=>x.id===old.id?record:x):[record,...all]);$('crmStatus').textContent='客戶資料已儲存。';$('crmStatus').className='status show ok'};
$('crmCheck').onclick=()=>{const r=scoreTrip({likes:$('crmLikes').value,avoids:$('crmAvoids').value},trip());$('crmStatus').textContent=r.conflicts.length?`不建議直接推薦：命中避開條件「${r.conflicts.join('、')}」。`:(r.matched.length?`適合推薦：符合「${r.matched.join('、')}」，適配分數 ${r.score}。`:'目前沒有足夠的偏好命中，建議再確認需求。');$('crmStatus').className='status show '+(r.suitable?'ok':'warn')};render()}
if(typeof document!=='undefined'){if(document.querySelector('.wrap > .panel'))install();else document.addEventListener('DOMContentLoaded',install)}return{scoreTrip}});
