/* Travel Assistant Pro 2.2 - per-departure price viewer */
(function(global,factory){const api=factory(global);if(typeof module==='object'&&module.exports)module.exports=api;global.TravelDailyPrices=api})(typeof window!=='undefined'?window:globalThis,function(global){
  'use strict';
  const clean=value=>String(value||'').trim();
  function normalizeDepartures(values){
    const map=new Map();
    (values||[]).forEach(item=>{const date=clean(item&&item.date).replace(/-/g,'/'),price=Number(String(item&&item.price||'').replace(/,/g,''));if(!/^20\d{2}\/\d{2}\/\d{2}$/.test(date)||!price)return;const code=clean(item.code).toUpperCase(),key=`${date}|${code||price}`;map.set(key,{date,code,price,seats:Number(item.seats)||0})});
    return [...map.values()].sort((a,b)=>a.date.localeCompare(b.date)||a.price-b.price);
  }
  function shortDate(value){const match=clean(value).match(/^20\d{2}\/(\d{2})\/(\d{2})$/);return match?`${Number(match[1])}/${Number(match[2])}`:clean(value)}
  function dailyPriceRows(values){const rows=normalizeDepartures(values),minimum=rows.length?Math.min(...rows.map(item=>item.price)):0;return rows.map(item=>({...item,label:shortDate(item.date),priceLabel:`${item.price.toLocaleString('zh-TW')} 元`,lowest:item.price===minimum}))}
  function marketingPriceText(values){const rows=dailyPriceRows(values);return rows.length?`\n\n💰 每日出發價格\n${rows.map(item=>`📅 ${item.label}｜${item.price.toLocaleString('zh-TW')} 元${item.lowest?'（最低價）':''}`).join('\n')}`:''}
  let departures=[],button=null,panel=null;
  function render(){const rows=dailyPriceRows(departures);if(button&&panel){button.disabled=!rows.length;button.textContent=panel.hidden?`顯示每日價格${rows.length?`（${rows.length}）`:''}`:'隱藏每日價格';panel.innerHTML=rows.length?rows.map(item=>`<div class="daily-price-row"><b>${item.label}</b><span>${item.priceLabel}${item.lowest?' <em>最低價</em>':''}</span></div>`).join(''):'<div class="small">尚未取得每日價格，請先使用「自動抓取並解析」。</div>'}const option=document.getElementById('includeDailyPricesInCopy'),note=document.getElementById('dailyPricesCopyNote');if(option){option.disabled=!rows.length;if(!rows.length)option.checked=false}if(note)note.textContent=rows.length?`已取得 ${rows.length} 個出發日價格`:'請先自動抓取行程，取得每日價格'}
  function setDepartures(values){departures=normalizeDepartures(values);if(panel)panel.hidden=true;render();return departures}
  function install(){if(typeof document==='undefined'||document.getElementById('toggleDailyPrices'))return;const proof=document.getElementById('proofPrice'),host=proof?.parentElement;if(!host)return;button=document.createElement('button');button.id='toggleDailyPrices';button.type='button';button.disabled=true;button.style.marginTop='8px';panel=document.createElement('div');panel.id='dailyPricePanel';panel.hidden=true;panel.className='hint';panel.style.marginTop='8px';button.onclick=()=>{panel.hidden=!panel.hidden;render()};host.append(button,panel);const copySection=document.querySelector('[data-tab="lineOut"]')?.closest('.section'),tabs=copySection?.querySelector('.tabs');if(copySection&&tabs&&!document.getElementById('includeDailyPricesInCopy')){const option=document.createElement('label');option.className='daily-price-copy-option';option.innerHTML='<input id="includeDailyPricesInCopy" type="checkbox"> <span><b>在文案顯示每日價格</b><small id="dailyPricesCopyNote">請先自動抓取行程，取得每日價格</small></span>';tabs.before(option);option.querySelector('input').addEventListener('change',()=>document.getElementById('generateCopy')?.click())}const style=document.createElement('style');style.textContent='.daily-price-row{display:flex;justify-content:space-between;gap:12px;padding:7px 2px;border-bottom:1px solid #dce9e7}.daily-price-row:last-child{border-bottom:0}.daily-price-row em{font-style:normal;font-size:11px;color:#087a55;background:#e7f8f2;padding:2px 6px;border-radius:999px}.daily-price-copy-option{display:flex;align-items:center;gap:9px;margin:10px 0;padding:10px 12px;border:1px solid #cfe3df;border-radius:12px;background:#f4faf8;cursor:pointer}.daily-price-copy-option input{width:18px;height:18px}.daily-price-copy-option span{display:flex;flex-direction:column;gap:2px}.daily-price-copy-option small{color:#607773}';document.head.appendChild(style);render()}
  if(typeof document!=='undefined'){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install()}
  function getDepartures(){return departures.slice()}
  return{normalizeDepartures,shortDate,dailyPriceRows,marketingPriceText,setDepartures,getDepartures,install};
});
